spring:
  application:
    name: cliente-service
server:
  port: 8183

eureka:
  client:
    fetch-registry: true   # true porque es cliente
    register-with-eureka: true    # true porque  es cliente
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost