
spring:
  application:
    name: iventario-service
    
server:
  port: 8182
  
springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CarritoCompraDTO?serverTimezone=America/Guayaquil&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

#spring.jpa.hibernate.ddl-auto: create
#spring.jpa.hibernate.ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: debug