spring:
  application:
    name: iventario-service
    
server:
  port: 8186
  
eureka:
  client:
    fetch-registry: true   # true porque es cliente
    register-with-eureka: true    # true porque  es cliente
    service-url:
      default-zone: http://localhost:8187/eureka
    instance:
      hostname: localhost