server:
  port: 8081
spring:
  cloud:     
     config:
       server:
          git:
           # default-label: config-server    #nommbre de la rama
            #default-label: eureka
            #default-label: multiple-instances 
            #default-label: gateway
            #default-label: circuit-breaker
            default-label: zipkin-sleuth
            uri: https://github.com/EdisonGarofalo1/PracticasMicroservices
            search-paths: config-data  # se guarda en una carpeta
  application:
    name: config-service    # nombre del proyecto    