server:
  port: 8081
spring:
  cloud:
     config:
       server:
          git:
            default-label: config-server    #nommbre de la rama
            uri: https://github.com/EdisonGarofalo1/PracticasMicroservices
            search-paths: config-data  # se guarda en una carpeta
  application:
    name: config-service    # nombre del proyecto    